spring:
  application:
    name: tally
  datasource:
    url: jdbc:postgresql://db.nzspwtddzemeryqtwhtz.supabase.co:5432/postgres?user=postgres&password=IAtMCPAU8hqCsZN4
    driver-class-name: org.postgresql.Driver
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 5050
  servlet:
    context-path: /api